image: node
script:
 - npm install
 - npm test
deploy:
  ssh:
    target: $$DOCKER_DEPLOY_USER@$$DOCKER_DEPLOY_IP:/containers/dronetest
    artifacts:
      - ./
    cmd: "cd /containers/dronetest && docker build -t doowb/dronetest . && docker run -p 8042:80 doowb/dronetest"

